#!/bin/sh
#
# live-i3: i3 specific setup for livesys
# SPDX-License-Identifier: GPL-3.0-or-later
#


# deactivate xfconf-migration (#683161)
rm -f /etc/xdg/autostart/xfconf-migration-4.6.desktop || :

# set up lightdm autologin
sed -i 's/^#autologin-user=.*/autologin-user=evernight/' /etc/lightdm/lightdm.conf
sed -i 's/^#autologin-user-timeout=.*/autologin-user-timeout=0/' /etc/lightdm/lightdm.conf
#sed -i 's/^#show-language-selector=.*/show-language-selector=true/' /etc/lightdm/lightdm-gtk-greeter.conf

# set i3 as default session, otherwise login will fail
sed -i 's/^#user-session=.*/user-session=i3/' /etc/lightdm/lightdm.conf

# Fix installer launch
# https://bugzilla.redhat.com/show_bug.cgi?id=2240823
cat > /etc/xdg/autostart/xfce-polkit.desktop <<EOF
[Desktop Entry]
Type=Application
Name=xfce-polkit
Exec=/usr/libexec/xfce-polkit
EOF

# Show harddisk install on the desktop
sed -i -e 's/NoDisplay=true/NoDisplay=false/' /usr/share/applications/liveinst.desktop
mkdir /home/evernight/Desktop

# setting the wallpaper
echo "/usr/bin/feh --bg-scale /usr/share/backgrounds/default.jxl" >> /home/evernight/.profile

# echoing type liveinst to start the installer
echo "echo 'Please type liveinst and press Enter to start the installer'" >> /home/evernight/.bashrc

# fixing the installer non opening bug
echo "xhost si:localuser:root" >> /home/evernight/.profile
