#!/bin/sh
#
# live-xfce: xfce specific setup for livesys
# SPDX-License-Identifier: GPL-3.0-or-later
#


mkdir -p /home/evernight/.config/xfce4

cat > /home/evernight/.config/xfce4/helpers.rc << FOE
MailReader=sylpheed-claws
FileManager=Thunar
WebBrowser=firefox
FOE

# disable screensaver locking (#674410)
cat >> /home/evernight/.xscreensaver << FOE
mode:           off
lock:           False
dpmsEnabled:    False
FOE

# deactivate xfconf-migration (#683161)
rm -f /etc/xdg/autostart/xfconf-migration-4.6.desktop || :

# deactivate xfce4-panel first-run dialog (#693569)
mkdir -p /home/evernight/.config/xfce4/xfconf/xfce-perchannel-xml
cp /etc/xdg/xfce4/panel/default.xml /home/evernight/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml

# set up lightdm autologin
sed -i 's/^#autologin-user=.*/autologin-user=evernight/' /etc/lightdm/lightdm.conf
sed -i 's/^#autologin-user-timeout=.*/autologin-user-timeout=0/' /etc/lightdm/lightdm.conf
#sed -i 's/^#show-language-selector=.*/show-language-selector=true/' /etc/lightdm/lightdm-gtk-greeter.conf

# set Xfce as default session, otherwise login will fail
sed -i 's/^#user-session=.*/user-session=xfce/' /etc/lightdm/lightdm.conf

# Show harddisk install on the desktop
sed -i -e 's/NoDisplay=true/NoDisplay=false/' /usr/share/applications/liveinst.desktop
mkdir /home/evernight/Desktop
cp /usr/share/applications/liveinst.desktop /home/evernight/Desktop

# no updater applet in live environment
rm -f /etc/xdg/autostart/org.mageia.dnfdragora-updater.desktop

# and mark it as executable (new Xfce security feature)
chmod +x /home/evernight/Desktop/liveinst.desktop

# set xfce-exe-checksum metadata to make the harddisk installer desktop icon trusted (#2172854)
LIVEINST_DESKTOP_CHECKSUM="$(sha256sum /home/evernight/Desktop/liveinst.desktop | awk '{print $1}')"
sudo -u evernight dbus-launch gio set -t string /home/evernight/Desktop/liveinst.desktop metadata::xfce-exe-checksum ${LIVEINST_DESKTOP_CHECKSUM}
