#!/bin/sh
#
# live-budgie: budgie-specific setup for livesys
# SPDX-License-Identifier: GPL-3.0-or-later
#

# make the installer show up
if [ -f /usr/share/applications/liveinst.desktop ]; then
  # Show harddisk install in Budgie Menu
  sed -i -e 's/NoDisplay=true/NoDisplay=false/' /usr/share/applications/liveinst.desktop
  # show up on budgie desktop view
  mkdir /home/evernight/Desktop
  cp /usr/share/applications/liveinst.desktop /home/evernight/Desktop
  chmod +x /home/evernight/Desktop/liveinst.desktop

  cat >> /usr/share/glib-2.0/schemas/com.solus-project.icon-tasklist.gschema.override << FOE
[com.solus-project.icon-tasklist]
pinned-launchers=['liveinst.desktop', 'org.kde.dolphin.desktop', 'org.mozilla.firefox.desktop', 'org.gnome.Rhythmbox3.desktop', 'org.kde.discover.desktop', 'org.xfce.Parole.desktop']
FOE

  cat >> /usr/share/glib-2.0/schemas/org.buddiesofbudgie.budgie-desktop-view.gschema.override << FOE
[org.buddiesofbudgie.budgie-desktop-view]
show=true
show-home-folder=false
FOE

  # Copy Anaconda branding in place
  if [ -d /usr/share/lorax/product/usr/share/anaconda ]; then
    cp -a /usr/share/lorax/product/* /
  fi
fi

DEFAULT_DESKTOP="budgie-desktop.desktop"
if [ -f /etc/sddm.conf ]; then
sed -i 's/^#User=.*/User=evernight/' /etc/sddm.conf
sed -i "s/^#Session=.*/Session=${DEFAULT_DESKTOP}/" /etc/sddm.conf
else
cat > /etc/sddm.conf << SDDM_EOF
[Autologin]
User=evernight
Session=${DEFAULT_DESKTOP}
SDDM_EOF
fi

# rebuild schema cache with any overrides we installed
glib-compile-schemas /usr/share/glib-2.0/schemas

# Turn off PackageKit-command-not-found while uninstalled
if [ -f /etc/PackageKit/CommandNotFound.conf ]; then
  sed -i -e 's/^SoftwareSourceSearch=true/SoftwareSourceSearch=false/' /etc/PackageKit/CommandNotFound.conf
fi
